### ISSUE TITLE
根据readme文件上的配置，数据渲染不出来？

### ISSUE THREAD

**Issue by liaowentao1016** [ddmy/vue-gantt#14]
![image](https://user-images.githubusercontent.com/69101087/221351189-fb189d4f-2c62-4129-82e8-afe6769b4051.png)

**Comment by liaowentao1016** [comment]
![image](https://user-images.githubusercontent.com/69101087/221351220-560aab37-9f7f-4de3-97e4-55d23f6cccc5.png)

**Comment by ddmy** [comment]
感谢使用 vue3-gantt, 当前控制台是否有报错或者告警信息？或者能否把代码贴出来让我这边运行查看？

在线demo查看 [vue3-gannt在线基础示例](https://codesandbox.io/s/jovial-volhard-rk1u3e?file=/src/App.vue)

**Comment by gdmec07150942** [comment]
我现在也是这个问题,有解决吗 

> ![image](https://user-images.githubusercontent.com/69101087/221351220-560aab37-9f7f-4de3-97e4-55d23f6cccc5.png)

我现在也是这个问题,有解决吗 ?

**Comment by gdmec07150942** [comment]
> 感谢使用 vue3-gantt, 当前控制台是否有报错或者告警信息？或者能否把代码贴出来让我这边运行查看？ @liaowentao1016
> 
> 在线demo查看 [vue3-gannt在线基础示例](https://codesandbox.io/s/jovial-volhard-rk1u3e?file=/src/App.vue)

没有报错,但是看着是样式问题导致的
