### ISSUE TITLE
当schedule为单个日期且在表格最后一列时显示不正常

### ISSUE THREAD

**Issue by xuejianma** [ddmy/vue-gantt#9]
![image](https://user-images.githubusercontent.com/26315299/211175093-f4afeae3-3ed9-4832-b695-9f92b83dc8d5.png)

**Comment by ddmy** [comment]
感谢使用`vue-gantt`。 
您那边能否提供一个最小可复现的demo？
根据你描述的情况，我这边尝试复现并未成功。
![image](https://user-images.githubusercontent.com/19168372/211261111-2dab2095-22ea-4eba-85c1-95719a9d7124.png)

**Comment by xuejianma** [comment]
感谢回复，下面是用例与截图。另外程序中标定的日期/dateRangeList与实际界面显示总有一天误差，不知道是否和此问题相关。
```
<template>
  <Gantt :data="data" itemText="项目" dateText="日期" :dateRangeList="dateRangeList" />
</template>

<script>
import { ref } from 'vue'
import Gantt from 'vue3-gantt'
import 'vue3-gantt/dist/style.css'
const dateRangeList = ref(['2022-04-01', '2022-04-05'])
const data = ref([
  {
    type: 'normal',
    color: '',
    name: '流星蝴蝶剑',
    schedule: [
      {
        id: 222221,
        name: '小年活动',
        desc: '这个活动很重要，6666666营收数百万，跨部门合作的一个大项目，BOSS亲自下场坐镇指挥，大家一定要团结一心!',
        backgroundColor: '#482',
        textColor: '#fff',
        days: ["2022-04-04", "2022-04-04"]
      }
    ],
  },
])

export default {
  name: 'TestPage',
  components: {
    Gantt,
  },
  setup() {
    return {
      data,
      dateRangeList,
    }
  },
}
</script>
```
![image](https://user-images.githubusercontent.com/26315299/211433395-f3f062e1-8906-4032-a986-e9595af9102d.png)

**Comment by ddmy** [comment]
> 感谢回复，下面是用例与截图。另外程序中标定的日期/dateRangeList与实际界面显示总有一天误差，不知道是否和此问题相关。

感谢,根据你提供的用例我并没有发现问题。

[参考在线codesandbox](https://codesandbox.io/s/jovial-volhard-rk1u3e?file=/src/App.vue)

**Comment by xuejianma** [comment]
感谢。可能是兼容性问题。ios手机端(safari/chrome)直接打开codesandbox问题不存在，PC windows11 (chrome/edge)打开相同的问题依旧存在。未测试macos。如下截图：
![image](https://user-images.githubusercontent.com/26315299/211446755-59e4d4b9-4cf1-4e9d-980d-0d2fe549598b.png)

**Comment by xuejianma** [comment]
感谢！打开上述codesandbox链接问题依旧存在，或许是平台环境问题？测试案例：
电脑端（PC win11）：
![image](https://user-images.githubusercontent.com/26315299/211465085-046c9458-a673-487c-89d1-51529c769067.png)
手机端（iOS Safari）：
![IMG_3058](https://user-images.githubusercontent.com/26315299/211465212-bfc55b2f-b1f0-4399-a5c9-817a2e0d3e79.PNG)

**Comment by ddmy** [comment]
> 感谢！打开上述codesandbox链接问题依旧存在，或许是平台环境问题？测试案例： 电脑端（PC win11）

我这边MAC safari版本`15.5 (17613.2.7.1.8)` 正常
MAC chrome 版本 `108.0.5359.124（正式版本） (x86_64)` 正常
`ios版本16.1.2 safari`浏览器 正常
![image](https://user-images.githubusercontent.com/19168372/211478594-a2958faf-2099-406b-a450-ffda8e671a24.png)

win11 chrome `版本 108.0.5359.125（正式版本） （64 位）` 正常

建议更新一下你的浏览器版本，提供一下具体的浏览器版本信息

**Comment by xuejianma** [comment]
感谢。多次尝试后发现可能是时区问题。
使用chrome的spoof timezone插件更改时区为UTC+任意小时，问题消失。更改时区为UTC-任意小时，问题复现。
另浏览器版本为Version 108.0.5359.125 (Official Build) (64-bit)
